
export const SequencerData = {
	assets: {
        autumn_leaves: "modules/jaamod/AnimatedArt/Assets/autumnLeaves.webm",
        beehive: "modules/jaamod/AnimatedArt/Assets/beehive.webm",
        bees: "modules/jaamod/AnimatedArt/Assets/bees.webm",
        bridge_planks: "modules/jaamod/AnimatedArt/Assets/bridgePlanks.webm",
        bubbles_popping: "modules/jaamod/AnimatedArt/Assets/bubblesPopping.webm",
        cauldrons: {
            green: "modules/jaamod/AnimatedArt/Assets/cauldronGreen.webm",
            red: "modules/jaamod/AnimatedArt/Assets/cauldronRed.webm"
        },
        chest_animated: {
            gold: "modules/jaamod/AnimatedArt/Assets/chestAnim-Gold.webm",
            empty: "modules/jaamod/AnimatedArt/Assets/chestAnimEmpty.webm",
            mimic: "modules/jaamod/AnimatedArt/Assets/chestAnimMimic.webm",
            potions: "modules/jaamod/AnimatedArt/Assets/chestAnimPotions.webm"
        },
        doors: {
            iron: "modules/jaamod/AnimatedArt/Assets/doorIron.webm",
            wood: [
                "modules/jaamod/AnimatedArt/Assets/doorWood.webm",
                "modules/jaamod/AnimatedArt/Assets/doorWood0.webm",
                "modules/jaamod/AnimatedArt/Assets/doorWood1.webm"
            ],
            double: "modules/jaamod/AnimatedArt/Assets/doubleDoor.webm"
        },
        dust_particles: [
            "modules/jaamod/AnimatedArt/Assets/dustParticles.webm",
            "modules/jaamod/AnimatedArt/Assets/dustParticles2.webm",
            "modules/jaamod/AnimatedArt/Assets/dustParticles3.webm"
        ],
        flies: "modules/jaamod/AnimatedArt/Assets/flies.webm",
        hexagram_spin: "modules/jaamod/AnimatedArt/Assets/hexagramSpin.webm",
        hummingbird: "modules/jaamod/AnimatedArt/Assets/hummingbird.webm",
        light_beam: "modules/jaamod/AnimatedArt/Assets/lightBeam.webm",
        moon_phase: "modules/jaamod/AnimatedArt/Assets/moonPhase.webm",
        old_door: "modules/jaamod/AnimatedArt/Assets/oldDoor.webm",
        pentagram_spin: "modules/jaamod/AnimatedArt/Assets/pentagramSpin.webm",
        portal_pull: "modules/jaamod/AnimatedArt/Assets/portalPull.webm",
        portal_pull_start: "modules/jaamod/AnimatedArt/Assets/portalPullStart.webm",
        rat_run_circle: "modules/jaamod/AnimatedArt/Assets/ratRunCircle.webm",
        trap_door: [
            "modules/jaamod/AnimatedArt/Assets/trapDoor.webm",
            "modules/jaamod/AnimatedArt/Assets/trapDoor1.webm"
        ],
        wagon_wheel_eft: "modules/jaamod/AnimatedArt/Assets/wagonWheelL.webm",
        wagon_wheel_right: "modules/jaamod/AnimatedArt/Assets/wagonWheelR.webm",
        water_caustics: "modules/jaamod/AnimatedArt/Assets/waterCaustics.webm",
        windmill: "modules/jaamod/AnimatedArt/Assets/windmill.webm",
        wooden_window: "modules/jaamod/AnimatedArt/Assets/windowWood.webm"
    },
    breath_weapon: {
        dragon_born_black_copper_acid_30x5_line: "modules/jaamod/AnimatedArt/Breath Weapon/dragonBornBlack-CopperAcid30x5Line.webm",
        dragon_born_blue_bronze_lightning_30x5_line: "modules/jaamod/AnimatedArt/Breath Weapon/dragonBornBlue-BronzeLightning30x5Line.webm",
        dragon_born_brass_fire_30x5_line: "modules/jaamod/AnimatedArt/Breath Weapon/dragonBornBrassFire30x5Line.webm",
        dragon_born_gold_red_fire15_cone: "modules/jaamod/AnimatedArt/Breath Weapon/dragonBornGold-RedFire15Cone.webm",
        dragon_born_green_poison15C_cone: "modules/jaamod/AnimatedArt/Breath Weapon/dragonBornGreenPoison15Cone.webm",
        dragon_born_silver_white_cold15_cone: "modules/jaamod/AnimatedArt/Breath Weapon/dragonBornSilver-WhiteCold15Cone.webm"
    },
    condition: {
        asleep: "modules/jaamod/AnimatedArt/Conditions/asleep.webm",
        asleep_circling: "modules/jaamod/AnimatedArt/Conditions/asleepC.webm",
        blessed: "modules/jaamod/AnimatedArt/Conditions/blessed.webm",
        blinded: "modules/jaamod/AnimatedArt/Conditions/blinded.webm",
        blood_drips: "modules/jaamod/AnimatedArt/Conditions/bloodDrips.webm",
        blood_drips_circle: "modules/jaamod/AnimatedArt/Conditions/bloodDripsCircle.webm",
        burning: "modules/jaamod/AnimatedArt/Conditions/burning.webm",
        charmed: "modules/jaamod/AnimatedArt/Conditions/charmed.webm",
        concentration: "modules/jaamod/AnimatedArt/Conditions/concentration.webm",
        cursed: "modules/jaamod/AnimatedArt/Conditions/cursed.webm",
        cursed_blue: "modules/jaamod/AnimatedArt/Conditions/cursedB.webm",
        dead_faint: "modules/jaamod/AnimatedArt/Conditions/dead2.webm",
        dead_curse: "modules/jaamod/AnimatedArt/Conditions/deadCurse.webm",
        deafened: "modules/jaamod/AnimatedArt/Conditions/deafened.webm",
        diseased: "modules/jaamod/AnimatedArt/Conditions/diseased.webm",
        exhaustion: {
            level1: "modules/jaamod/AnimatedArt/Conditions/exhaustion1.webm",
            level2: "modules/jaamod/AnimatedArt/Conditions/exhaustion2.webm",
            level3: "modules/jaamod/AnimatedArt/Conditions/exhaustion3.webm",
            level4: "modules/jaamod/AnimatedArt/Conditions/exhaustion4.webm",
            level5: "modules/jaamod/AnimatedArt/Conditions/exhaustion5.webm",
            level6: "modules/jaamod/AnimatedArt/Conditions/exhaustion6.webm"
        },
        fire_shield: "modules/jaamod/AnimatedArt/Conditions/fireShield.webm",
        flying: "modules/jaamod/AnimatedArt/Conditions/flying.webm",
        frightened: "modules/jaamod/AnimatedArt/Conditions/frightened.webm",
        frozen: "modules/jaamod/AnimatedArt/Conditions/frozen.webm",
        grappled: "modules/jaamod/AnimatedArt/Conditions/grappled.webm",
        hexed: "modules/jaamod/AnimatedArt/Conditions/hexed.webm",
        incapacitated: "modules/jaamod/AnimatedArt/Conditions/incapacitated.webm",
        invisible: "modules/jaamod/AnimatedArt/Conditions/invisible.webm",
        magic_shield: "modules/jaamod/AnimatedArt/Conditions/magicShield.webm",
        paralyzed: "modules/jaamod/AnimatedArt/Conditions/paralyzed.webm",
        petrified: "modules/jaamod/AnimatedArt/Conditions/petrified.webm",
        poisoned: "modules/jaamod/AnimatedArt/Conditions/poisoned.webm",
        prone: "modules/jaamod/AnimatedArt/Conditions/prone.webm",
        raging: "modules/jaamod/AnimatedArt/Conditions/raging.webm",
        restrained: "modules/jaamod/AnimatedArt/Conditions/restrained.webm",
        stunned: "modules/jaamod/AnimatedArt/Conditions/stunned.webm",
        unconscious: "modules/jaamod/AnimatedArt/Conditions/unconscious.webm",
        rings: {
            asleep: "modules/jaamod/AnimatedArt/Conditions/asleepR.webm",
            bleeding: "modules/jaamod/AnimatedArt/Conditions/bleedingR.webm",
            blessed: "modules/jaamod/AnimatedArt/Conditions/blessedR.webm",
            blinded: "modules/jaamod/AnimatedArt/Conditions/blindedR.webm",
            burning: "modules/jaamod/AnimatedArt/Conditions/burningR.webm",
            charmed: "modules/jaamod/AnimatedArt/Conditions/charmedR.webm",
            concentrating: "modules/jaamod/AnimatedArt/Conditions/concentratingR.webm",
            cursed: "modules/jaamod/AnimatedArt/Conditions/cursedR.webm",
            dead: "modules/jaamod/AnimatedArt/Conditions/deadR.webm",
            deafened: "modules/jaamod/AnimatedArt/Conditions/deafenedR.webm",
            diseased: "modules/jaamod/AnimatedArt/Conditions/diseasedR.webm",
            exhaustion: {
                level1: "modules/jaamod/AnimatedArt/Conditions/exhaustion1R.webm",
                level2: "modules/jaamod/AnimatedArt/Conditions/exhaustion2R.webm",
                level3: "modules/jaamod/AnimatedArt/Conditions/exhaustion3R.webm",
                level4: "modules/jaamod/AnimatedArt/Conditions/exhaustion4R.webm",
                level5: "modules/jaamod/AnimatedArt/Conditions/exhaustion5R.webm"
            },
            flying: "modules/jaamod/AnimatedArt/Conditions/flyingR.webm",
            frightened: "modules/jaamod/AnimatedArt/Conditions/frightenedR.webm",
            grappled: "modules/jaamod/AnimatedArt/Conditions/grappledR.webm",
            hexed: "modules/jaamod/AnimatedArt/Conditions/hexedR.webm",
            incapacitated: "modules/jaamod/AnimatedArt/Conditions/incapacitatedR.webm",
            invisible: "modules/jaamod/AnimatedArt/Conditions/invisibleR.webm",
            paralyzed: "modules/jaamod/AnimatedArt/Conditions/paralyzedR.webm",
            petrified: "modules/jaamod/AnimatedArt/Conditions/petrifiedR.webm",
            poisoned: "modules/jaamod/AnimatedArt/Conditions/poisonedR.webm",
            prone: "modules/jaamod/AnimatedArt/Conditions/proneR.webm",
            raging: "modules/jaamod/AnimatedArt/Conditions/ragingR.webm",
            restrained: "modules/jaamod/AnimatedArt/Conditions/restrainedR.webm",
            stunned: "modules/jaamod/AnimatedArt/Conditions/stunnedR.webm",
            unconscious: "modules/jaamod/AnimatedArt/Conditions/unconsciousR.webm"
        }
    },
    fire: {
        campfire: "modules/jaamod/AnimatedArt/Fire/campfire.webm",
        candle: "modules/jaamod/AnimatedArt/Fire/candle.webm",
        candle_flame: [
            "modules/jaamod/AnimatedArt/Fire/candleFlame.webm",
            "modules/jaamod/AnimatedArt/Fire/candleFlame2.webm",
            "modules/jaamod/AnimatedArt/Fire/candleFlame3.webm"
        ],
        canonfire: "modules/jaamod/AnimatedArt/Fire/canonfire.webm",
        fire_blast: [
            "modules/jaamod/AnimatedArt/Fire/fireBlast.webm",
            "modules/jaamod/AnimatedArt/Fire/fireBlastS.webm"
        ],
        fire_breath: [
            "modules/jaamod/AnimatedArt/Fire/fireBreath.webm",
            "modules/jaamod/AnimatedArt/Fire/fireBreathMESS.webm"
        ],
        fire_burn: "modules/jaamod/AnimatedArt/Fire/fireBurn.webm",
        fire_flat: "modules/jaamod/AnimatedArt/Fire/fireFlat.webm",
        fire_loop3: "modules/jaamod/AnimatedArt/Fire/fireLoop3.webm",
        fire_loop_iso: "modules/jaamod/AnimatedArt/Fire/fireLoopISO.webm",
        fire_ring: [
            "modules/jaamod/AnimatedArt/Fire/fireRing.webm",
            "modules/jaamod/AnimatedArt/Fire/fireRing2.webm",
            "modules/jaamod/AnimatedArt/Fire/fireRing3.webm",
            "modules/jaamod/AnimatedArt/Fire/fireRing4.webm",
            "modules/jaamod/AnimatedArt/Fire/fireRingBlue.webm"
        ],
        fire_top: [
            "modules/jaamod/AnimatedArt/Fire/fireTop.webm",
            "modules/jaamod/AnimatedArt/Fire/fireTop6.webm",
            "modules/jaamod/AnimatedArt/Fire/fireTopType2.webm"
        ],
        fire_torch_small: "modules/jaamod/AnimatedArt/Fire/fireTorchSmall.webm",
        fire_trap1: "modules/jaamod/AnimatedArt/Fire/fireTrap1.webm",
        fire: [
            "modules/jaamod/AnimatedArt/Fire/fireType1.webm",
            "modules/jaamod/AnimatedArt/Fire/fireType2.webm"
        ],
        fireblast_mess: "modules/jaamod/AnimatedArt/Fire/fireblastMESS.webm",
        fuse_burning: "modules/jaamod/AnimatedArt/Fire/fuseBurning.webm",
        fuse_new: "modules/jaamod/AnimatedArt/Fire/fuseNew.webm",
        hell_portal_fire: "modules/jaamod/AnimatedArt/Fire/hellPortalFire.webm",
        wall_torch: [
            "modules/jaamod/AnimatedArt/Fire/walltorch.webm",
            "modules/jaamod/AnimatedArt/Fire/wallTorch2.webm"
        ]
    },
    misc: {
        count_down_100_seconds: "modules/jaamod/AnimatedArt/Misc/100secondCountdown.webm",
        count_down_60_seconds: "modules/jaamod/AnimatedArt/Misc/60secondCountdown.webm",
        arrow_blue: "modules/jaamod/AnimatedArt/Misc/ArrowBlue.webm",
        poi: "modules/jaamod/AnimatedArt/Misc/POI.webm",
        qm: "modules/jaamod/AnimatedArt/Misc/QM.webm",
        qm_swarm: "modules/jaamod/AnimatedArt/Misc/QMSwarm.webm",
        tv_horse: "modules/jaamod/AnimatedArt/Misc/TVHorse.webm",
        tv_static: "modules/jaamod/AnimatedArt/Misc/TVstatic.webm",
        acid_pool: "modules/jaamod/AnimatedArt/Misc/acidPool.webm",
        balls: "modules/jaamod/AnimatedArt/Misc/balls.webm",
        bard_song_color: "modules/jaamod/AnimatedArt/Misc/bardSongColor.webm",
        bat_swarm: "modules/jaamod/AnimatedArt/Misc/batSwarm.webm",
        beam_spin: "modules/jaamod/AnimatedArt/Misc/beamSpin.webm",
        beehive: "modules/jaamod/AnimatedArt/Misc/beehive.webm",
        bees: "modules/jaamod/AnimatedArt/Misc/bees.webm",
        blast1: "modules/jaamod/AnimatedArt/Misc/blast1.webm",
        blue_sphere: "modules/jaamod/AnimatedArt/Misc/blueSphere.webm",
        boom: [
            "modules/jaamod/AnimatedArt/Misc/boom2.webm",
            "modules/jaamod/AnimatedArt/Misc/boom4.webm",
            "modules/jaamod/AnimatedArt/Misc/boom5.webm",
            "modules/jaamod/AnimatedArt/Misc/boom6.webm",
            "modules/jaamod/AnimatedArt/Misc/boom7.webm",
            "modules/jaamod/AnimatedArt/Misc/boom8.webm"
        ],
        bottle: {
            blue: "modules/jaamod/AnimatedArt/Misc/bottleBlue.webm",
            green: "modules/jaamod/AnimatedArt/Misc/bottleGreen.webm",
            purple: "modules/jaamod/AnimatedArt/Misc/bottlePurple.webm",
            red1: "modules/jaamod/AnimatedArt/Misc/bottleRed.1.webm"
        },
        burst: [
            "modules/jaamod/AnimatedArt/Misc/burst8.webm",
            "modules/jaamod/AnimatedArt/Misc/burst9.webm",
            "modules/jaamod/AnimatedArt/Misc/burst10.webm",
            "modules/jaamod/AnimatedArt/Misc/burst14.webm"
        ],
        chain_figure8: "modules/jaamod/AnimatedArt/Misc/chainFigure8.webm",
        curses: "modules/jaamod/AnimatedArt/Misc/curses.webm",
        dust_devil: "modules/jaamod/AnimatedArt/Misc/dustDevil.webm",
        dust_fountain: "modules/jaamod/AnimatedArt/Misc/dustFountain.webm",
        dust_poof: "modules/jaamod/AnimatedArt/Misc/dustPoof.webm",
        dust_storm: "modules/jaamod/AnimatedArt/Misc/dustStorm.webm",
        electrified_circle: "modules/jaamod/AnimatedArt/Misc/electrifiedCircle.webm",
        electrified_square: "modules/jaamod/AnimatedArt/Misc/electrifiedSquare.webm",
        emerging_arms: "modules/jaamod/AnimatedArt/Misc/emergingArms.webm",
        emerging_arms_three: "modules/jaamod/AnimatedArt/Misc/emergingArmsThree.webm",
        eyes_blink: {
            blue: "modules/jaamod/AnimatedArt/Misc/eyesBlinkBlue.webm",
            green: "modules/jaamod/AnimatedArt/Misc/eyesBlinkGreen.webm",
            red: "modules/jaamod/AnimatedArt/Misc/eyesBlinkRed.mov.webm",
            yellow: "modules/jaamod/AnimatedArt/Misc/eyesBlinkYellow.webm"
        },
        fire_boom: "modules/jaamod/AnimatedArt/Misc/fireBoom.webm",
        fireflies: "modules/jaamod/AnimatedArt/Misc/fireflies.webm",
        fireworks: [
            "modules/jaamod/AnimatedArt/Misc/fireworks1.webm",
            "modules/jaamod/AnimatedArt/Misc/fireworks2.webm",
        ],
        fish_school: "modules/jaamod/AnimatedArt/Misc/fishSchool.webm",
        fish_school_shadow: "modules/jaamod/AnimatedArt/Misc/fishSchoolShadow.webm",
        flag: {
            black: "modules/jaamod/AnimatedArt/Misc/flagBlack.webm",
            blue: "modules/jaamod/AnimatedArt/Misc/flagBlue.webm",
            green: "modules/jaamod/AnimatedArt/Misc/flagGreen.webm",
            orange: "modules/jaamod/AnimatedArt/Misc/flagOrange.webm",
            red: "modules/jaamod/AnimatedArt/Misc/flagRed.webm",
            white: "modules/jaamod/AnimatedArt/Misc/flagWhite.webm",
            yellow: "modules/jaamod/AnimatedArt/Misc/flagYellow.webm"
        },
        flies: "modules/jaamod/AnimatedArt/Misc/flies.webm",
        fountain_spray: [
            "modules/jaamod/AnimatedArt/Misc/fountainSpray.webm",
            "modules/jaamod/AnimatedArt/Misc/fountainSpray2.webm",
            "modules/jaamod/AnimatedArt/Misc/fountainSpray3.webm"
        ],
        freezing_blast: "modules/jaamod/AnimatedArt/Misc/freezingBlast.webm",
        glass_shatter: "modules/jaamod/AnimatedArt/Misc/glassShatter.webm",
        glow_sprite: [
            "modules/jaamod/AnimatedArt/Misc/glowSprite1.webm",
            "modules/jaamod/AnimatedArt/Misc/glowSprite2.webm",
            "modules/jaamod/AnimatedArt/Misc/glowSprite3.webm",
            "modules/jaamod/AnimatedArt/Misc/glowSprite4.webm"
        ],
        gold_coin: "modules/jaamod/AnimatedArt/Misc/goldCoin.webm",
        grass2: "modules/jaamod/AnimatedArt/Misc/grass2.webm",
        gray_arrow: "modules/jaamod/AnimatedArt/Misc/gray_arrow.webm",
        green_crystal: "modules/jaamod/AnimatedArt/Misc/greenCrystal.mov.webm",
        guardian_portrait: [
            "modules/jaamod/AnimatedArt/Misc/guardianPortrait.webm",
            "modules/jaamod/AnimatedArt/Misc/guardianPortrait2.webm"
        ],
        gun_muzzle_flash: "modules/jaamod/AnimatedArt/Misc/gunMuzzleFlash.webm",
        hail_of_bullets: "modules/jaamod/AnimatedArt/Misc/hailOfBullets.webm",
        hell_portal: "modules/jaamod/AnimatedArt/Misc/hellPortal.webm",
        ice_burst: "modules/jaamod/AnimatedArt/Misc/iceBurst.webm",
        important_dark: "modules/jaamod/AnimatedArt/Misc/importantDark.webm",
        important_light: "modules/jaamod/AnimatedArt/Misc/importantLight.webm",
        lava_burst: "modules/jaamod/AnimatedArt/Misc/lavaBurst.webm",
        light_beam: {
            blue: "modules/jaamod/AnimatedArt/Misc/lightBeamBlue.webm",
            cyan: "modules/jaamod/AnimatedArt/Misc/lightBeamCyan.webm",
            green: "modules/jaamod/AnimatedArt/Misc/lightBeamGreen.webm",
            red: "modules/jaamod/AnimatedArt/Misc/lightBeamRed.webm",
            white: "modules/jaamod/AnimatedArt/Misc/lightBeamWhite.webm"
        },
        lighthouse_light: "modules/jaamod/AnimatedArt/Misc/lighthouseLight.webm",
        lightning_ball: "modules/jaamod/AnimatedArt/Misc/lightningBall.webm",
        lightning_bolt: "modules/jaamod/AnimatedArt/Misc/lightningBolt.webm",
        mirror_crystal: "modules/jaamod/AnimatedArt/Misc/mirrorCrystal.webm",
        murky_water: "modules/jaamod/AnimatedArt/Misc/murkyWater.webm",
        ocean_tile_1024x1024: "modules/jaamod/AnimatedArt/Misc/oceanTile1024x1024.webm",
        on_deck1: "modules/jaamod/AnimatedArt/Misc/onDeck1.webm",
        party: "modules/jaamod/AnimatedArt/Misc/party.webm",
        party_marker: "modules/jaamod/AnimatedArt/Misc/partyMarker.webm",
        party_people: "modules/jaamod/AnimatedArt/Misc/partyPeople.webm",
        party_yah: "modules/jaamod/AnimatedArt/Misc/partyYAH.webm",
        patrol_droid: "modules/jaamod/AnimatedArt/Misc/patrolDroid.webm",
        pointer: "modules/jaamod/AnimatedArt/Misc/pointer.webm",
        portal3: "modules/jaamod/AnimatedArt/Misc/portal3.webm",
        portal7: "modules/jaamod/AnimatedArt/Misc/portal7.webm",
        portal_blue: "modules/jaamod/AnimatedArt/Misc/portalBlue.webm",
        propeller_spin: "modules/jaamod/AnimatedArt/Misc/propellerSpin.webm",
        rainbow: "modules/jaamod/AnimatedArt/Misc/rainbow.webm",
        ship_wooden_sailing_1k: "modules/jaamod/AnimatedArt/Misc/shipWoodenSailing1k.webm",
        snowfall_2: "modules/jaamod/AnimatedArt/Misc/snowfall2.webm",
        snowfall_2k: "modules/jaamod/AnimatedArt/Misc/snowfall2k.webm",
        snowfall_light: "modules/jaamod/AnimatedArt/Misc/snowfallLight.webm",
        spin5: "modules/jaamod/AnimatedArt/Misc/spin5.webm",
        spinburst2: "modules/jaamod/AnimatedArt/Misc/spinburst2.webm",
        star_field4k_alpha: "modules/jaamod/AnimatedArt/Misc/starField4kAlpha.webm",
        starfield: "modules/jaamod/AnimatedArt/Misc/starfield.webm",
        starfield_nebula: "modules/jaamod/AnimatedArt/Misc/starfieldWnebula.webm",
        sunflower: "modules/jaamod/AnimatedArt/Misc/sunflower.webm",
        tree: "modules/jaamod/AnimatedArt/Misc/tree.webm",
        underwater1k: "modules/jaamod/AnimatedArt/Misc/underwater1k.webm",
        water_pool: "modules/jaamod/AnimatedArt/Misc/waterPool.webm",
        water_splash3: "modules/jaamod/AnimatedArt/Misc/waterSplash3.webm",
        waterfall_small: "modules/jaamod/AnimatedArt/Misc/waterfallSmall.webm",
        welder_sparks: "modules/jaamod/AnimatedArt/Misc/welderSparks.webm",
        yellow_crystal: "modules/jaamod/AnimatedArt/Misc/yellowCrystal.webm"
    },
    runes: {
        circle: {
            circle1_2: "modules/jaamod/AnimatedArt/Runes/circle1.2.webm",
            circle1: "modules/jaamod/AnimatedArt/Runes/circle1.mov.webm",
            circle_teal_purple: "modules/jaamod/AnimatedArt/Runes/circleTealPurple.webm",
            circ: "modules/jaamod/AnimatedArt/Runes/circletealPurpleGlow.webm"
        },
        rune_2_1: "modules/jaamod/AnimatedArt/Runes/rune.2.1.webm",
        rune_1_1: "modules/jaamod/AnimatedArt/Runes/rune1.1.webm",
        rune_1_2: "modules/jaamod/AnimatedArt/Runes/rune1.2.webm",
        rune_1_3: "modules/jaamod/AnimatedArt/Runes/rune1.3.webm",
        rune_1_4: "modules/jaamod/AnimatedArt/Runes/rune1.4.webm",
        teleportation_circle: {
            teleportation_circle2: "modules/jaamod/AnimatedArt/Runes/teleportationCircle2.webm",
            teleportation_circle3: "modules/jaamod/AnimatedArt/Runes/teleportationCircle3.webm",
            teleportation_circle4: "modules/jaamod/AnimatedArt/Runes/teleportationCircle4.webm"
        }
    },
    sci_fi: {
        asteroid: "modules/jaamod/AnimatedArt/SciFi/asteroid.webm",
        asteroid2: "modules/jaamod/AnimatedArt/SciFi/asteroid2.webm",
        blue: "modules/jaamod/AnimatedArt/SciFi/blueWarningLightFast.webm",
        fingerprint_scan: "modules/jaamod/AnimatedArt/SciFi/fingerprintScan.webm",
        gun_muzzle_flash: "modules/jaamod/AnimatedArt/SciFi/gunMuzzleFlash.webm",
        photon_torpedo: "modules/jaamod/AnimatedArt/SciFi/photonTorpedo.webm",
        plasma_torpedo: "modules/jaamod/AnimatedArt/SciFi/plasmaTorpedo.webm",
        red_planet: "modules/jaamod/AnimatedArt/SciFi/redPlanet.webm",
        red_warning_light: "modules/jaamod/AnimatedArt/SciFi/redWarningLight.webm",
        red_warning_light_fast: "modules/jaamod/AnimatedArt/SciFi/redWarningLightFast.webm",
        rocket2: "modules/jaamod/AnimatedArt/SciFi/rocket2.webm",
        sci_fi_hud: "modules/jaamod/AnimatedArt/SciFi/sciFiHUD.webm",
        sci_fi_hud2: "modules/jaamod/AnimatedArt/SciFi/sciFiHUD2.webm",
        teleporter: "modules/jaamod/AnimatedArt/SciFi/teleporter.webm",
        welder_sparks: "modules/jaamod/AnimatedArt/SciFi/welderSparks.webm"
    },
    sequencer_fx_master: {
        contagion: "modules/jaamod/AnimatedArt/SequencerFXMaster/Contagion.webm",
        mm2: "modules/jaamod/AnimatedArt/SequencerFXMaster/MM2.webm",
        mmimpact: "modules/jaamod/AnimatedArt/SequencerFXMaster/MMimpact.webm",
        blood_splat: {
            black: "modules/jaamod/AnimatedArt/SequencerFXMaster/bloodSplatBlack.webm",
            blue: "modules/jaamod/AnimatedArt/SequencerFXMaster/bloodSplatBlue.webm",
            green: "modules/jaamod/AnimatedArt/SequencerFXMaster/bloodSplatGreen.webm",
            purple: "modules/jaamod/AnimatedArt/SequencerFXMaster/bloodSplatPurple.webm",
            red: [
                "modules/jaamod/AnimatedArt/SequencerFXMaster/bloodSplatRed1.webm",
                "modules/jaamod/AnimatedArt/SequencerFXMaster/bloodSplatRed2.webm",
                "modules/jaamod/AnimatedArt/SequencerFXMaster/bloodSplatRed3.webm",
                "modules/jaamod/AnimatedArt/SequencerFXMaster/bloodSplatRed4.webm",
                "modules/jaamod/AnimatedArt/SequencerFXMaster/bloodSplatRed5.webm"
            ]
        },
        boom: [
            "modules/jaamod/AnimatedArt/SequencerFXMaster/boom1.webm",
            "modules/jaamod/AnimatedArt/SequencerFXMaster/boom2.webm",
            "modules/jaamod/AnimatedArt/SequencerFXMaster/boom3.webm",
            "modules/jaamod/AnimatedArt/SequencerFXMaster/boom4.webm",
            "modules/jaamod/AnimatedArt/SequencerFXMaster/boom5.webm",
            "modules/jaamod/AnimatedArt/SequencerFXMaster/boom6.webm",
            "modules/jaamod/AnimatedArt/SequencerFXMaster/boom7.webm",
            "modules/jaamod/AnimatedArt/SequencerFXMaster/boom8.webm"
        ],
        eldritch_blast1: "modules/jaamod/AnimatedArt/SequencerFXMaster/eldritchBlast1.webm",
        fire_bolt: [
            "modules/jaamod/AnimatedArt/SequencerFXMaster/fireBolt.webm",
            "modules/jaamod/AnimatedArt/SequencerFXMaster/fireBolt2.webm",
            "modules/jaamod/AnimatedArt/SequencerFXMaster/fireBolt2a.webm"
        ],
        fire_impact: "modules/jaamod/AnimatedArt/SequencerFXMaster/fireImpact.webm",
        fire_impact_sm: "modules/jaamod/AnimatedArt/SequencerFXMaster/fireImpactSm.webm",
        green_ray: "modules/jaamod/AnimatedArt/SequencerFXMaster/greenRay.webm",
        green_ray_impact: "modules/jaamod/AnimatedArt/SequencerFXMaster/greenRayImpact.webm",
        guiding_bolt: "modules/jaamod/AnimatedArt/SequencerFXMaster/guidingBolt.webm",
        lightning_blue: "modules/jaamod/AnimatedArt/SequencerFXMaster/lightningBlue.webm",
        lightning_bolt_yellow: "modules/jaamod/AnimatedArt/SequencerFXMaster/lightningBoltYellow.webm",
        missile_blue: "modules/jaamod/AnimatedArt/SequencerFXMaster/missileBlue.webm",
        projectile: {
            blue: "modules/jaamod/AnimatedArt/SequencerFXMaster/projectileBlue.webm",
            green: "modules/jaamod/AnimatedArt/SequencerFXMaster/projectileGreen.webm",
            purple: "modules/jaamod/AnimatedArt/SequencerFXMaster/projectilePurple.webm",
            red: "modules/jaamod/AnimatedArt/SequencerFXMaster/projectileRed.webm",
            yellow: "modules/jaamod/AnimatedArt/SequencerFXMaster/projectileYellow.webm"
        },
        spinburst2: "modules/jaamod/AnimatedArt/SequencerFXMaster/spinburst2.webm",
        vector_boom: {
            blue: "modules/jaamod/AnimatedArt/SequencerFXMaster/vectorBoomBlue.webm",
            green: "modules/jaamod/AnimatedArt/SequencerFXMaster/vectorBoomGreen.webm",
            purple: "modules/jaamod/AnimatedArt/SequencerFXMaster/vectorBoomPurple.webm",
            red: "modules/jaamod/AnimatedArt/SequencerFXMaster/vectorBoomRed.webm",
            yellow: "modules/jaamod/AnimatedArt/SequencerFXMaster/vectorBoomYellow.webm"
        }
    },
    smoke: {
        poison_cloud: "modules/jaamod/AnimatedArt/Smoke/poisonCloud.webm",
        top_down: {
            black: "modules/jaamod/AnimatedArt/Smoke/smokeBlackTopDown.webm",
            blue: "modules/jaamod/AnimatedArt/Smoke/smokeBlueTopDown.webm",
            cyan: "modules/jaamod/AnimatedArt/Smoke/smokeCyanTopDown.webm",
            green: "modules/jaamod/AnimatedArt/Smoke/smokeGreenTopDown.webm",
            orange: "modules/jaamod/AnimatedArt/Smoke/smokeOrangeTopDown.webm",
            purple: "modules/jaamod/AnimatedArt/Smoke/smokePurpleTopDown.webm",
            red: "modules/jaamod/AnimatedArt/Smoke/smokeRedTopDown.webm",
            white: "modules/jaamod/AnimatedArt/Smoke/smokeWhiteTopDown.webm",
            yellow: "modules/jaamod/AnimatedArt/Smoke/smokeYellowTopDown.webm"
        },
        thick: {
            black: "modules/jaamod/AnimatedArt/Smoke/smokeBlackThick.webm",
            white: "modules/jaamod/AnimatedArt/Smoke/smokeWhiteThick.webm"
        },
        cel: "modules/jaamod/AnimatedArt/Smoke/smokeCel.webm",
        lite: "modules/jaamod/AnimatedArt/Smoke/smokeLite.webm",
        color: {
            blue: "modules/jaamod/AnimatedArt/Smoke/smokeBlue.webm",
            cyan: "modules/jaamod/AnimatedArt/Smoke/smokeCyan.webm",
            green: "modules/jaamod/AnimatedArt/Smoke/smokeGreen.webm",
            orange: "modules/jaamod/AnimatedArt/Smoke/smokeOrange.webm",
            purple: "modules/jaamod/AnimatedArt/Smoke/smokePurple.webm",
            red: "modules/jaamod/AnimatedArt/Smoke/smokeRed.webm",
            white: "modules/jaamod/AnimatedArt/Smoke/smokeWhite.webm",
            yellow: "modules/jaamod/AnimatedArt/Smoke/smokeYellow.webm"
        }
    },
    spells_effects: {
        aganazzars_scorcher: "modules/jaamod/AnimatedArt/Spells-Effects/AganazzarsScorcher.webm",
        aganazzars_scorcher_mess: "modules/jaamod/AnimatedArt/Spells-Effects/AganazzarsScorcherMESS.webm",
        antilife_shell: "modules/jaamod/AnimatedArt/Spells-Effects/AntilifeShell.webm",
        armsof_hadar: "modules/jaamod/AnimatedArt/Spells-Effects/ArmsofHadar.webm",
        armsof_hadar2: "modules/jaamod/AnimatedArt/Spells-Effects/ArmsofHadar2.webm",
        auraof_vitality: "modules/jaamod/AnimatedArt/Spells-Effects/AuraofVitality.webm",
        bigbys_hand: "modules/jaamod/AnimatedArt/Spells-Effects/BigbysHand.webm",
        faerie_fire_blue: "modules/jaamod/AnimatedArt/Spells-Effects/FaerieFireBlue.webm",
        faerie_fire_green: "modules/jaamod/AnimatedArt/Spells-Effects/FaerieFireGreen.webm",
        faerie_fire_violet: "modules/jaamod/AnimatedArt/Spells-Effects/FaerieFireViolet.webm",
        fear: "modules/jaamod/AnimatedArt/Spells-Effects/Fear.webm",
        incendiary_cloud: "modules/jaamod/AnimatedArt/Spells-Effects/IncendiaryCloud.webm",
        insect_plague0: "modules/jaamod/AnimatedArt/Spells-Effects/InsectPlague.0.webm",
        leomunds_tiny_hut0: "modules/jaamod/AnimatedArt/Spells-Effects/LeomundsTinyHut.0.webm",
        lightning_bolt: "modules/jaamod/AnimatedArt/Spells-Effects/LighningBolt.webm",
        mordenkainens_magnificent_mansion: "modules/jaamod/AnimatedArt/Spells-Effects/MordenkainensMagnificentMansion.webm",
        shatter: "modules/jaamod/AnimatedArt/Spells-Effects/Shatter.webm",
        acid_spray: "modules/jaamod/AnimatedArt/Spells-Effects/acidSpray.webm",
        acid_spray_mess: "modules/jaamod/AnimatedArt/Spells-Effects/acidSprayMESS.webm",
        alarm: "modules/jaamod/AnimatedArt/Spells-Effects/alarm.webm",
        animated_objects_coppers: "modules/jaamod/AnimatedArt/Spells-Effects/animatedObjectsCoppers.webm",
        animated_objects_gold: "modules/jaamod/AnimatedArt/Spells-Effects/animatedObjectsGold.webm",
        auraof_life: "modules/jaamod/AnimatedArt/Spells-Effects/auraOfLife.webm",
        black_tentacle2: "modules/jaamod/AnimatedArt/Spells-Effects/blackTentacle.2.webm",
        blade_barrier: "modules/jaamod/AnimatedArt/Spells-Effects/bladeBarrier.webm",
        blade_barrier_pf2e: "modules/jaamod/AnimatedArt/Spells-Effects/bladeBarrierPF2E.webm",
        burning_hands: "modules/jaamod/AnimatedArt/Spells-Effects/burningHands.webm",
        call_lightning: "modules/jaamod/AnimatedArt/Spells-Effects/callLightning.webm",
        chain1: "modules/jaamod/AnimatedArt/Spells-Effects/chain1.webm",
        chain2: "modules/jaamod/AnimatedArt/Spells-Effects/chain2.webm",
        circleof_death: "modules/jaamod/AnimatedArt/Spells-Effects/circleOfDeath.webm",
        cloud_kill: "modules/jaamod/AnimatedArt/Spells-Effects/cloudKill.webm",
        cloudof_daggers_l: "modules/jaamod/AnimatedArt/Spells-Effects/cloudOfDaggersL.webm",
        cloudof_daggers_s: "modules/jaamod/AnimatedArt/Spells-Effects/cloudOfDaggersS.webm",
        color_spray: "modules/jaamod/AnimatedArt/Spells-Effects/colorSpray.webm",
        color_spray_mess: "modules/jaamod/AnimatedArt/Spells-Effects/colorSprayMESS.webm",
        color_spray_mess_f: "modules/jaamod/AnimatedArt/Spells-Effects/colorSprayMESSF.mov.webm",
        coneof_cold4: "modules/jaamod/AnimatedArt/Spells-Effects/coneOfCold4.webm",
        confusion: "modules/jaamod/AnimatedArt/Spells-Effects/confusion.webm",
        dancing_lights: "modules/jaamod/AnimatedArt/Spells-Effects/dancingLights.webm",
        darkness: "modules/jaamod/AnimatedArt/Spells-Effects/darkness.webm",
        dawn: "modules/jaamod/AnimatedArt/Spells-Effects/dawn.webm",
        destructive_wave: "modules/jaamod/AnimatedArt/Spells-Effects/destructiveWave.webm",
        earth_tremor: "modules/jaamod/AnimatedArt/Spells-Effects/earthTremor.webm",
        ensnaring_strike: "modules/jaamod/AnimatedArt/Spells-Effects/ensnaringStrike.webm",
        entangle: "modules/jaamod/AnimatedArt/Spells-Effects/entangle.webm",
        entangle2: "modules/jaamod/AnimatedArt/Spells-Effects/entangle2.webm",
        faerie_fire: {
            blue: "modules/jaamod/AnimatedArt/Spells-Effects/faerieFireBlue2.webm",
            green: "modules/jaamod/AnimatedArt/Spells-Effects/faerieFireGreen2.webm",
            violet: "modules/jaamod/AnimatedArt/Spells-Effects/faerieFireViolet2.webm"
        },
        fear2: "modules/jaamod/AnimatedArt/Spells-Effects/fear2.webm",
        fire_wall: "modules/jaamod/AnimatedArt/Spells-Effects/fireWall.webm",
        fireball: "modules/jaamod/AnimatedArt/Spells-Effects/fireball.webm",
        flaming_sphere: "modules/jaamod/AnimatedArt/Spells-Effects/flamingSphere.webm",
        flaming_sphere_s: "modules/jaamod/AnimatedArt/Spells-Effects/flamingSphereS.webm",
        fog_cloud: "modules/jaamod/AnimatedArt/Spells-Effects/fogCloud.webm",
        glyphof_warding: "modules/jaamod/AnimatedArt/Spells-Effects/glyphOfWarding.webm",
        grease: "modules/jaamod/AnimatedArt/Spells-Effects/grease.webm",
        gustof_wind: "modules/jaamod/AnimatedArt/Spells-Effects/gustOfWind.webm",
        hallucinatory_terrain0: "modules/jaamod/AnimatedArt/Spells-Effects/hallucinatoryTerrain.0.webm",
        hallucinatory_terrain: "modules/jaamod/AnimatedArt/Spells-Effects/hallucinatoryTerrain.webm",
        horrid_wilting: "modules/jaamod/AnimatedArt/Spells-Effects/horridWilting.webm",
        ice_storm: "modules/jaamod/AnimatedArt/Spells-Effects/iceStorm.webm",
        maelstrom: "modules/jaamod/AnimatedArt/Spells-Effects/maelstrom.webm",
        magic_missile_test: [
            "modules/jaamod/AnimatedArt/Spells-Effects/magicMissile.test.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/magicMissile.test2.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/magicMissile.test3.webm"
        ],
        magic_missile: "modules/jaamod/AnimatedArt/Spells-Effects/magicMissile.webm",
        meteor_swarm: "modules/jaamod/AnimatedArt/Spells-Effects/meteorSwarm.webm",
        moonbeam: [
            "modules/jaamod/AnimatedArt/Spells-Effects/moonbeam1.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/moonbeam2.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/moonbeam3.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/moonbeam4.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/moonbeam5.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/moonbeam6.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/moonbeam7.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/moonbeam8.webm"
        ],
        poison_spray: "modules/jaamod/AnimatedArt/Spells-Effects/poisonSpray.webm",
        prismatic_spray_mess_f: "modules/jaamod/AnimatedArt/Spells-Effects/prismaticSprayMESSF.webm",
        shatter1: "modules/jaamod/AnimatedArt/Spells-Effects/shatter.1.webm",
        sleet_storm: "modules/jaamod/AnimatedArt/Spells-Effects/sleetStorm.webm",
        spirit_gauntlet: "modules/jaamod/AnimatedArt/Spells-Effects/spiritGuantlet.webm",
        spirit_guardians_trans50: "modules/jaamod/AnimatedArt/Spells-Effects/spiritGuardians-trans50.webm",
        spirit_guardians: "modules/jaamod/AnimatedArt/Spells-Effects/spiritGuardians.webm",
        old: "modules/jaamod/AnimatedArt/Spells-Effects/spiritGuardiansOLD.webm",
        spirit_mace: "modules/jaamod/AnimatedArt/Spells-Effects/spiritMace.webm",
        spiritual_weapon_mace: "modules/jaamod/AnimatedArt/Spells-Effects/spiritualWeaponMace.webm",
        spiritual_weapon_maul: "modules/jaamod/AnimatedArt/Spells-Effects/spiritualWeaponMaul.webm",
        spiritual_weapon_maul_gray: "modules/jaamod/AnimatedArt/Spells-Effects/spiritualWeaponMaulGray.webm",
        spiritual_weapon_sword: "modules/jaamod/AnimatedArt/Spells-Effects/spiritualWeaponSword.webm",
        spiritual_weapon_sword_gray: "modules/jaamod/AnimatedArt/Spells-Effects/spiritualWeaponSwordGray.webm",
        sunbeam: "modules/jaamod/AnimatedArt/Spells-Effects/sunbeam.webm",
        sunburst: "modules/jaamod/AnimatedArt/Spells-Effects/sunburst.webm",
        swarm_spider: "modules/jaamod/AnimatedArt/Spells-Effects/swarmSpider.webm",
        tentacles_black: "modules/jaamod/AnimatedArt/Spells-Effects/tentaclesBlack.webm",
        tentacles_black2: "modules/jaamod/AnimatedArt/Spells-Effects/tentaclesBlack2.webm",
        thunder_wave: [
            "modules/jaamod/AnimatedArt/Spells-Effects/thunderWave.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/thunderWaveC.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/thunderWaveC1.webm",
            "modules/jaamod/AnimatedArt/Spells-Effects/thunderWaveOld.webm"
        ],
        vines4: "modules/jaamod/AnimatedArt/Spells-Effects/vines4.webm"
    },
    traps: {
        spikes_trap_d: "modules/jaamod/AnimatedArt/Traps/SpikesTrapD.webm",
        spikes_trap_f: "modules/jaamod/AnimatedArt/Traps/SpikesTrapF.webm",
        bear_trap: "modules/jaamod/AnimatedArt/Traps/bearTrap.webm",
        bear_trap_s: "modules/jaamod/AnimatedArt/Traps/bearTrapS.webm",
        blade_trap: "modules/jaamod/AnimatedArt/Traps/bladeTrap.webm",
        bolt_trap: "modules/jaamod/AnimatedArt/Traps/boltTrap.webm",
        lever_side: "modules/jaamod/AnimatedArt/Traps/leverSide.webm",
        lever_switch: "modules/jaamod/AnimatedArt/Traps/leverSwitch.webm",
        lever_switch90: "modules/jaamod/AnimatedArt/Traps/leverSwitch90.webm",
        lever_yellow_floor: "modules/jaamod/AnimatedArt/Traps/leverYellowFloor.mov.webm",
        lever_yellow_wall: "modules/jaamod/AnimatedArt/Traps/leverYellowWall.webm",
        lever_yellow_wall90: "modules/jaamod/AnimatedArt/Traps/leverYellowWall90.mov.webm",
        pit_trap: "modules/jaamod/AnimatedArt/Traps/pitTrap.webm",
        pit_trap_transparent: "modules/jaamod/AnimatedArt/Traps/pitTrapTransparent.webm",
        pit_trap_type2: "modules/jaamod/AnimatedArt/Traps/pitTrapType2.webm",
        pit_trap_no_spikes: "modules/jaamod/AnimatedArt/Traps/pitTrap_noSpikes.webm",
        pit_trap_no_walls: "modules/jaamod/AnimatedArt/Traps/pitTrap_noWalls.webm",
        saw_blade: "modules/jaamod/AnimatedArt/Traps/sawBlade.webm",
        saw_blade_cell: "modules/jaamod/AnimatedArt/Traps/sawBladeCell.webm",
        saw_blade_cell_shade_floor_iso: "modules/jaamod/AnimatedArt/Traps/sawBladeCellShadeFloorISO.webm",
        saw_blade_half: "modules/jaamod/AnimatedArt/Traps/sawBladeHalf.webm",
        saw_blade_half_static: "modules/jaamod/AnimatedArt/Traps/sawBladeHalfStatic.webm",
        spike_splat: "modules/jaamod/AnimatedArt/Traps/spikeSplat.webm",
        spike_trap: "modules/jaamod/AnimatedArt/Traps/spikeTrap.webm",
        trap_net: "modules/jaamod/AnimatedArt/Traps/trapNet.webm",
        trap_net_dark: "modules/jaamod/AnimatedArt/Traps/trapNetDark.webm",
        trap_smash_ffm: "modules/jaamod/AnimatedArt/Traps/trapsmashFFM.webm"
    }
};